HOST="https://www.yinhu.com"
INDEXPAGE="${HOST}/loan/ajax_loan_list.bl"
POSTDATA="pageNo=\${i}"
DETAILPAGE1="${HOST}/loan/loan_detail.bl?loanNo="
DETAILPAGE2="${HOST}/loan/ajax_credit_list.bl"
POSTDATA2="loanId=\${value}&creditPageNo=\${i}"
#COOKIE=`cat COOKIE`
#GETPAGE="wget --no-cookies --header=\"Cookie: ${COOKIE}\" --header=\"User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36\" --keep-session-cookie"
#GETPAGE="wget --no-cookies --header=\"Cookie: ${COOKIE}\" --keep-session-cookie"
GETPAGE="wget"
