HOST='http://www.itbt.com.cn'
INDEXPAGE="${HOST}/index.php?s=/Invest/GetBorrowlist"
DETAILPAGE="${HOST}/Invest/ViewBorrow/ibid/"
INVESTORPAGE="${HOST}/index.php?s=/Invest/Getlytb"
GETPAGE="wget"
INDPOSTDATA='mode=1&tpage%5Bpage%5D='
INDPOSTDATA1='&tpage%5Bsize%5D=20&sel%5Bselecttype%5D=0&sel%5Bselectdate%5D=0&sel%5Bselectreplay%5D=0&sel%5Bselectstate%5D=0&sel%5Bdeadline%5D=0&sel%5Baprrange%5D=0&sel%5Baccount%5D=0&sel%5Bmyname%5D=&sel%5Bselectname%5D=0'
INVPOSTDATA='tpage%5Bpage%5D='
INVPOSTDATA1='&tpage%5Bsize%5D=10&ibnum='
